apiVersion: v1
kind: Secret
metadata:
  name: mongodb
  labels:
    app.kubernetes.io/component: mongodb
    {{- include "catalogue.labels" . | nindent 4 }}
type: Opaque
data:
  catalogue_mongo_url: {{ .Values.catalogueMongoUrl | b64enc }}